---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-capi-operator
  namespace: openshift-cluster-api
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    release.openshift.io/feature-gate: "TechPreviewNoUpgrade"
  labels:
    k8s-app: cluster-capi-operator
spec:
  selector:
    matchLabels:
      k8s-app: cluster-capi-operator
  replicas: 1
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        k8s-app: cluster-capi-operator
    spec:
      serviceAccountName: cluster-capi-operator
      containers:
      - name: cluster-capi-operator
        image: registry.ci.openshift.org/openshift:cluster-capi-operator
        command:
        - ./cluster-capi-operator
        args:
          - --images-json=/etc/cluster-api-config-images/images.json
          - --providers-yaml=/etc/cluster-api-config-providers/providers-list.yaml
        env:
        - name: RELEASE_VERSION
          value: "0.0.1-snapshot"
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        volumeMounts:
        - name: images
          mountPath: /etc/cluster-api-config-images/
        - name: providers
          mountPath: /etc/cluster-api-config-providers/
      - name: user-data-secret-controller
        image: registry.ci.openshift.org/openshift:cluster-capi-operator
        command:
          - ./user-data-secret-controller
        args:
          - --leader-elect=true
          - --leader-elect-lease-duration=137s
          - --leader-elect-renew-deadline=107s
          - --leader-elect-retry-period=26s
          - --leader-elect-resource-namespace=openshift-cluster-api
        resources:
          requests:
            cpu: 10m
            memory: 25Mi
      - name: cluster-controller
        image: registry.ci.openshift.org/openshift:cluster-capi-operator
        command:
          - ./cluster-controller
        args:
          - --leader-elect=true
          - --leader-elect-lease-duration=137s
          - --leader-elect-renew-deadline=107s
          - --leader-elect-retry-period=26s
          - --leader-elect-resource-namespace=openshift-cluster-api
        resources:
          requests:
            cpu: 10m
            memory: 25Mi
        volumeMounts:
        - name: providers
          mountPath: /etc/cluster-api-config-providers/
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: system-node-critical
      restartPolicy: Always
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: images
        configMap:
          defaultMode: 420
          name: cluster-capi-operator-images
      - name: providers
        configMap:
          defaultMode: 420
          name: cluster-capi-operator-providers
