apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: cluster-api
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/core: capi-operator
    control-plane: controller-manager
  name: capi-operator-controller-manager
  namespace: openshift-cluster-api
spec:
  replicas: 1
  selector:
    matchLabels:
      clusterctl.cluster.x-k8s.io/core: capi-operator
      control-plane: controller-manager
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        clusterctl.cluster.x-k8s.io/core: capi-operator
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
      - args:
        - --metrics-bind-addr=127.0.0.1:8080
        - --leader-elect
        command:
        - /bin/cluster-api-operator
        image: gcr.io/openshift-gce-devel/cluster-api-operator-amd64:dev
        name: manager
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
      priorityClassName: system-cluster-critical
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
status: {}
